<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOrGkalB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOrGkalB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOrGkalB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOrGkalB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOrGkalB\App_KernelDevDebugContainer([
    'container.build_hash' => 'OrGkalB',
    'container.build_id' => '85db0daa',
    'container.build_time' => 1709668911,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOrGkalB');
