<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBs1nxL5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBs1nxL5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBs1nxL5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBs1nxL5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBs1nxL5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bs1nxL5',
    'container.build_id' => '79bfecb3',
    'container.build_time' => 1709637712,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBs1nxL5');
